#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MVCSample;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ApiTest.cshtml")]
    public partial class _Views_Home_ApiTest_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_ApiTest_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\ApiTest.cshtml"
   Layout = null;
            
            #line default
            #line hidden
WriteLiteral("\r\n<html>\r\n<head>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 45), Tuple.Create("\"", 81)
, Tuple.Create(Tuple.Create("", 52), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/layui/css/layui.css")
, 52), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n<body>\r\n<fieldset");

WriteLiteral(" class=\"layui-elem-field layui-field-title\"");

WriteLiteral(" style=\"margin-top: 10px;\"");

WriteLiteral(">\r\n    <legend>本页面接口测试,{layim}为默认startup中的配置前缀，可以改成自定义路径</legend>\r\n</fieldset>\r\n<" +
"table");

WriteLiteral(" class=\"layui-table\"");

WriteLiteral(" lay-even=\"\"");

WriteLiteral(" lay-skin=\"nob\"");

WriteLiteral(">\r\n    <colgroup>\r\n        <col");

WriteLiteral(" width=\"150\"");

WriteLiteral(">\r\n        <col");

WriteLiteral(" width=\"150\"");

WriteLiteral(">\r\n        <col");

WriteLiteral(" width=\"200\"");

WriteLiteral(@">
        <col>
    </colgroup>
    <thead>
        <tr>
            <th>接口名称</th>
            <th>url</th>
            <th>请求方式</th>
            <th>参数要求</th>
            <th>试一试</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>添加群组</td>
            <td>/{layim}/group/add</td>
            <td>POST</td>
            <td>当前用户ID（uid）<br/>群组名称（name）<br />群组描述(desc)<br />群组图片(avatar)</td>
            <td><button");

WriteLiteral(" class=\"layui-btn layui-btn-primary layui-btn-small\"");

WriteLiteral(" api-event=\"groupadd\"");

WriteLiteral(">试一试</button></td>\r\n        </tr>\r\n        <tr>\r\n            <td>添加用户</td>\r\n     " +
"       <td>/{layim}/user/add</td>\r\n            <td>POST</td>\r\n            <td>用户" +
"昵称（name）<br/>用户头像（avatar）<br/>签名(sign)</td>\r\n            <td><button");

WriteLiteral(" class=\"layui-btn layui-btn-primary layui-btn-small\"");

WriteLiteral(" api-event=\"useradd\"");

WriteLiteral(">试一试</button></td>\r\n        </tr>\r\n        <tr>\r\n            <td>申请好友</td>\r\n     " +
"       <td>/{layim}/friend/apply</td>\r\n            <td>POST</td>\r\n            <t" +
"d>申请人ID(uid)<br/>被申请人ID(tid)<br/>备注(other)</td>\r\n            <td><button");

WriteLiteral(" class=\"layui-btn layui-btn-primary layui-btn-small\"");

WriteLiteral(" api-event=\"friendapply\"");

WriteLiteral(">试一试</button></td>\r\n        </tr>\r\n        <tr>\r\n            <td>申请加群</td>\r\n     " +
"       <td>/{layim}/group/apply</td>\r\n            <td>POST</td>\r\n            <td" +
">申请人ID(uid)<br/>群组ID(tid)<br/>备注(other)</td>\r\n            <td><button");

WriteLiteral(" class=\"layui-btn layui-btn-primary layui-btn-small\"");

WriteLiteral(" api-event=\"groupapply\"");

WriteLiteral(">试一试</button></td>\r\n        </tr>\r\n        <tr>\r\n            <td>用户查找</td>\r\n     " +
"       <td>/{layim}/user/search</td>\r\n            <td>GET</td>\r\n            <td>" +
"起始序号(start)<br/>条数(num)<br/>关键词.目前只支持昵称(key)<br/>排序按照注册时间正序</td>\r\n            <t" +
"d><button");

WriteLiteral(" class=\"layui-btn layui-btn-primary layui-btn-small\"");

WriteLiteral(" api-event=\"usersearch\"");

WriteLiteral(">试一试</button></td>\r\n        </tr>\r\n        <tr>\r\n            <td>群组查找</td>\r\n     " +
"       <td>/{layim}/group/search</td>\r\n            <td>GET</td>\r\n            <td" +
">起始序号(start)<br/>条数(num)<br/>关键词.目前只支持群名(key)<br/>排序按照添加时间正序</td>\r\n            <" +
"td><button");

WriteLiteral(" class=\"layui-btn layui-btn-primary layui-btn-small\"");

WriteLiteral(" api-event=\"groupsearch\"");

WriteLiteral(">试一试</button></td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2589), Tuple.Create("\"", 2619)
, Tuple.Create(Tuple.Create("", 2595), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/layui/layui.js")
, 2595), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        var prefix = \"/layim\";\r\n        layui.use([\'jqu" +
"ery\', \'layer\'], function ($, l) {\r\n            var layer = l;\r\n            $(fun" +
"ction () {\r\n                $(\'[api-event]*\').on(\'click\', function (e) {\r\n      " +
"              var event = $(this).attr(\'api-event\');\r\n                    test.r" +
"equest(event);\r\n                });\r\n            });\r\n\r\n\r\n            var api = " +
"[\r\n                { name: \'添加群组\', func: \'groupadd\', url: \'/group/add\', params: " +
"[\'uid\', \'name\', \'desc\', \'avatar\'], type: \'POST\' },\r\n                { name: \'添加用" +
"户\', func: \'useradd\', url: \'/user/add\', params: [\'name\', \'avatar\', \'sign\'], type:" +
" \'POST\' },\r\n                { name: \'申请好友\', func: \'friendapply\', url: \'/friend/a" +
"pply\', params: [\'uid\', \'tid\', \'other\'], type: \'POST\' },\r\n                { name:" +
" \'申请加群\', func: \'groupapply\', url: \'/group/apply\', params: [\'uid\', \'tid\', \'other\'" +
"], type: \'POST\' },\r\n                { name: \'用户查找\', func: \'usersearch\', url: \'/u" +
"ser/search\', params: [\'start\', \'num\', \'key\'], type: \'GET\' },\r\n                { " +
"name: \'群组查找\', func: \'groupsearch\', url: \'/group/search\', params: [\'start\', \'num\'" +
", \'key\'], type: \'GET\' }\r\n            ];\r\n\r\n            var test = {\r\n           " +
"     request: function (o) {\r\n                    var detail = api.filter(functi" +
"on (item) {\r\n                        return item.func == o\r\n                    " +
"})[0];\r\n\r\n                    var html = (function () {\r\n                       " +
" var t = \'<div>\';\r\n                        for (var i = 0; i < detail.params.len" +
"gth; i++) {\r\n                            t += \'<input type=\"text\" name=\"\' + o + " +
"\'\" data-param=\"\' + detail.params[i] + \'\" placeholder=\"\' + detail.params[i] + \'\" " +
"class=\"layui-input\" style=\"margin:2px;\">\'\r\n                        }\r\n          " +
"              t += \'</div>\';\r\n                        return t;\r\n               " +
"     })();\r\n                    var url = prefix + detail.url;\r\n                " +
"    var d = function (func) {\r\n                        var data = {};\r\n         " +
"               $(\'input[name=\"\' + func + \'\"]\').each(function () {\r\n             " +
"               var p = $(this).data(\'param\'), val = $(this).val();\r\n            " +
"                data[p] = val;\r\n                        })\r\n                    " +
"    return data;\r\n                    };\r\n                    layer.confirm(html" +
", {\r\n                        title: detail.name\r\n                   , shade: [0." +
"8, \'#393D49\'],\r\n                        yes: function (index) {\r\n               " +
"             $.ajax({\r\n                                url: url,\r\n              " +
"                  type: detail.type,\r\n                                data: d(o)" +
",\r\n                                success: function (res) {\r\n                  " +
"                  console.log(res);\r\n                                    layer.m" +
"sg(res.msg||\'请查看console\');\r\n                                }\r\n                 " +
"           });\r\n                        }\r\n                    });\r\n            " +
"    }\r\n            };\r\n\r\n        });\r\n    </script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
