#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Home\HistoryMessageView.cshtml"
    using LayIM.NetClient.Model;
    
    #line default
    #line hidden
    using MVCSample;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/HistoryMessageView.cshtml")]
    public partial class _Views_Home_HistoryMessageView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_HistoryMessageView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Home\HistoryMessageView.cshtml"
  
    var models = new List<LayimChatMessageViewModel>()
    {
        new LayimChatMessageViewModel { uid=1, self=true, name="小盘子", content="hello", avatar="", addtime="2017-06-08 17:32" },
        new LayimChatMessageViewModel { uid=1, self=false, name="小盘子", content="hello", avatar="", addtime="2017-06-08 17:32" }
    };

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Home\HistoryMessageView.cshtml"
 foreach (var item in models)
            {
                if (item.self)
                {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" trans=\"0\"");

WriteLiteral(" class=\"layim-chat-mine\"");

WriteLiteral(" data-timestamp=\"");

            
            #line 14 "..\..\Views\Home\HistoryMessageView.cshtml"
                                                         Write(item.timestamp);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 609), Tuple.Create("\"", 627)
            
            #line 16 "..\..\Views\Home\HistoryMessageView.cshtml"
, Tuple.Create(Tuple.Create("", 615), Tuple.Create<System.Object, System.Int32>(item.avatar
            
            #line default
            #line hidden
, 615), false)
);

WriteLiteral(" />\r\n                <cite><i>");

            
            #line 17 "..\..\Views\Home\HistoryMessageView.cshtml"
                    Write(item.addtime);

            
            #line default
            #line hidden
WriteLiteral("</i>");

            
            #line 17 "..\..\Views\Home\HistoryMessageView.cshtml"
                                     Write(item.name);

            
            #line default
            #line hidden
WriteLiteral("</cite>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 20 "..\..\Views\Home\HistoryMessageView.cshtml"
           Write(item.content);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </li>\r\n");

            
            #line 23 "..\..\Views\Home\HistoryMessageView.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <li");

WriteLiteral(" trans=\"0\"");

WriteLiteral(" data-timestamp=\"");

            
            #line 26 "..\..\Views\Home\HistoryMessageView.cshtml"
                                 Write(item.timestamp);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"layim-chat-user\"");

WriteLiteral(">\r\n                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 967), Tuple.Create("\"", 985)
            
            #line 28 "..\..\Views\Home\HistoryMessageView.cshtml"
, Tuple.Create(Tuple.Create("", 973), Tuple.Create<System.Object, System.Int32>(item.avatar
            
            #line default
            #line hidden
, 973), false)
);

WriteLiteral(" />\r\n                <cite>");

            
            #line 29 "..\..\Views\Home\HistoryMessageView.cshtml"
                 Write(item.name);

            
            #line default
            #line hidden
WriteLiteral("<i>");

            
            #line 29 "..\..\Views\Home\HistoryMessageView.cshtml"
                              Write(item.addtime);

            
            #line default
            #line hidden
WriteLiteral("</i></cite>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"layim-chat-text\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Home\HistoryMessageView.cshtml"
           Write(item.content);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </li>\r\n");

            
            #line 35 "..\..\Views\Home\HistoryMessageView.cshtml"
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
