#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayIM.NetClient
{
    using System;
    using System.Collections.Generic;

#line 1 "..\..\Views\Home\HistoryMessageView.cshtml"
    using LayIM.NetClient;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class HistoryMessagePage : RazorPage
    {
        /// <summary>
        /// 初始化参数
        /// </summary>
        private void initParam()
        {
            _param = new Model.LayimHistoryParam
            {
                UserId = Query("uid").ToInt64(),//当前用户ID
                ToId = Query("id").ToInt64(),
                Type = Query("type"),
                Page = Query("page").ToInt32(),
                MsgTimestamp = Query("stamp").ToInt64()
            };
        }
        public override void Execute()
        {
            //先给参数赋值
            initParam();
            //获取model列表
            var models = Storage.GetConnection().GetHistoryMessages(_param);
            string classUser = "layim-chat-user";
            string classMine = "layim-chat-mine";
            foreach (var item in models)
            {
                WriteLiteral($"<li trans=\"0\" class=\"{(item.self ? classMine : classUser) }\" data-timestamp=\"{item.timestamp}\">\r\n");
                WriteLiteral("<div class=\"layim-chat-user\">\r\n");
                WriteLiteral($"<img src=\"{item.avatar}\" />\r\n");
                if (item.self)
                {
                    WriteLiteral($"<cite><i>{item.addtime}</i>{item.name}</cite>\r\n");
                }
                else {
                    WriteLiteral($"<cite><i>{item.name}</i>{item.addtime}</cite>\r\n");
                }
                WriteLiteral("</div>\r\n");
                WriteLiteral("<div class=\"layim-chat-text\">\r\n");
                WriteLiteral($"{item.content}");
                WriteLiteral("</div>\r\n");
                WriteLiteral("</li>\r\n");
            }
        }
    }
}
#pragma warning restore 1591
